apiVersion: v1
kind: Service
metadata:
  name: gorgon
  namespace: gorgon
  labels:
    app.kubernetes.io/name: gorgon
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8501
      protocol: TCP
  selector:
    app: gorgon
